<?php
/**
 * Export Excel Controller
 * Exports sales report to Excel/CSV format
 */

require_once '../../config/db.php';

// Check authentication and authorization
if (!isLoggedIn()) {
    die(json_encode(['success' => false, 'message' => 'Unauthorized - Please log in']));
}

if (!hasRole('Manager', 'Administrator')) {
    die(json_encode(['success' => false, 'message' => 'Access denied - Manager role required']));
}

$month = $_GET['month'] ?? null;
$year = $_GET['year'] ?? null;

if (!$month || !$year) {
    die('Month and year are required');
}

try {
    $db = getDB();
    
    // Get summary data
    $summaryStmt = $db->prepare("
        SELECT 
            COUNT(*) as total_orders,
            SUM(total_amount) as total_revenue,
            AVG(total_amount) as average_order_value,
            SUM(CASE WHEN order_status = 'Delivered' THEN 1 ELSE 0 END) as completed_orders
        FROM orders
        WHERE MONTH(order_date) = :month 
        AND YEAR(order_date) = :year
    ");
    
    $summaryStmt->execute(['month' => $month, 'year' => $year]);
    $summary = $summaryStmt->fetch();
    
    // Get best sellers
    $bestSellersStmt = $db->prepare("
        SELECT 
            m.meal_name,
            c.category_name,
            SUM(oi.quantity) as total_quantity,
            SUM(oi.subtotal) as total_revenue,
            COUNT(DISTINCT o.order_id) as order_count
        FROM order_items oi
        INNER JOIN meals m ON oi.meal_id = m.meal_id
        INNER JOIN categories c ON m.category_id = c.category_id
        INNER JOIN orders o ON oi.order_id = o.order_id
        WHERE MONTH(o.order_date) = :month 
        AND YEAR(o.order_date) = :year
        AND o.order_status = 'Delivered'
        GROUP BY m.meal_id
        ORDER BY total_quantity DESC
    ");
    
    $bestSellersStmt->execute(['month' => $month, 'year' => $year]);
    $bestSellers = $bestSellersStmt->fetchAll();
    
    // Get daily sales
    $dailySalesStmt = $db->prepare("
        SELECT 
            DATE(order_date) as sale_date,
            COUNT(*) as order_count,
            SUM(total_amount) as daily_revenue
        FROM orders
        WHERE MONTH(order_date) = :month 
        AND YEAR(order_date) = :year
        AND order_status = 'Delivered'
        GROUP BY DATE(order_date)
        ORDER BY sale_date
    ");
    
    $dailySalesStmt->execute(['month' => $month, 'year' => $year]);
    $dailySales = $dailySalesStmt->fetchAll();
    
    $monthName = date('F', mktime(0, 0, 0, $month, 1));
    
    // Set headers for CSV download (Excel can open CSV files)
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="sales-report-' . $month . '-' . $year . '.csv"');
    
    // Create output stream
    $output = fopen('php://output', 'w');
    
    // Write header
    fputcsv($output, ['Aunt Joy\'s Restaurant - Sales Report']);
    fputcsv($output, ['Report Period:', "$monthName $year"]);
    fputcsv($output, ['Generated:', date('F j, Y, g:i a')]);
    fputcsv($output, ['Generated By:', $_SESSION['full_name']]);
    fputcsv($output, []); // Empty row
    
    // Write summary section
    fputcsv($output, ['SUMMARY STATISTICS']);
    fputcsv($output, ['Metric', 'Value']);
    fputcsv($output, ['Total Revenue', formatCurrency($summary['total_revenue'] ?? 0)]);
    fputcsv($output, ['Total Orders', $summary['total_orders'] ?? 0]);
    fputcsv($output, ['Average Order Value', formatCurrency($summary['average_order_value'] ?? 0)]);
    fputcsv($output, ['Completed Orders', $summary['completed_orders'] ?? 0]);
    fputcsv($output, []); // Empty row
    
    // Write best sellers section
    fputcsv($output, ['TOP SELLING ITEMS']);
    fputcsv($output, ['Rank', 'Item Name', 'Category', 'Quantity Sold', 'Total Revenue', 'Orders']);
    
    $rank = 1;
    foreach ($bestSellers as $item) {
        fputcsv($output, [
            $rank++,
            $item['meal_name'],
            $item['category_name'],
            $item['total_quantity'],
            formatCurrency($item['total_revenue']),
            $item['order_count']
        ]);
    }
    
    fputcsv($output, []); // Empty row
    
    // Write daily sales section
    fputcsv($output, ['DAILY SALES BREAKDOWN']);
    fputcsv($output, ['Date', 'Orders', 'Revenue']);
    
    foreach ($dailySales as $day) {
        fputcsv($output, [
            $day['sale_date'],
            $day['order_count'],
            formatCurrency($day['daily_revenue'])
        ]);
    }
    
    fputcsv($output, []); // Empty row
    fputcsv($output, ['End of Report']);
    
    fclose($output);
    exit();
    
} catch (PDOException $e) {
    die('Failed to generate Excel: ' . $e->getMessage());
}

/**
 * NOTE: For proper Excel files (.xlsx), install PhpSpreadsheet:
 * 
 * 1. Install via Composer: composer require phpoffice/phpspreadsheet
 * 2. Use this code instead:
 * 
 * require 'vendor/autoload.php';
 * use PhpOffice\PhpSpreadsheet\Spreadsheet;
 * use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
 * 
 * $spreadsheet = new Spreadsheet();
 * $sheet = $spreadsheet->getActiveSheet();
 * $sheet->setCellValue('A1', 'Sales Report');
 * // Add more data...
 * 
 * $writer = new Xlsx($spreadsheet);
 * header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
 * header('Content-Disposition: attachment;filename="sales-report.xlsx"');
 * $writer->save('php://output');
 */
?>