<?php
/**
 * Export PDF Controller
 * Exports sales report to PDF format
 * Note: In production, use a library like TCPDF or FPDF
 */

require_once '../../config/db.php';

// Check authentication and authorization
if (!isLoggedIn()) {
    die(json_encode(['success' => false, 'message' => 'Unauthorized - Please log in']));
}

if (!hasRole('Manager', 'Administrator')) {
    die(json_encode(['success' => false, 'message' => 'Access denied - Manager role required']));
}

$month = $_GET['month'] ?? null;
$year = $_GET['year'] ?? null;

if (!$month || !$year) {
    die('Month and year are required');
}

try {
    $db = getDB();
    
    // Get report data
    $summaryStmt = $db->prepare("
        SELECT 
            COUNT(*) as total_orders,
            SUM(total_amount) as total_revenue,
            AVG(total_amount) as average_order_value
        FROM orders
        WHERE MONTH(order_date) = :month 
        AND YEAR(order_date) = :year
        AND order_status = 'Delivered'
    ");
    
    $summaryStmt->execute(['month' => $month, 'year' => $year]);
    $summary = $summaryStmt->fetch();
    
    // Get best sellers
    $bestSellersStmt = $db->prepare("
        SELECT 
            m.meal_name,
            SUM(oi.quantity) as total_quantity,
            SUM(oi.subtotal) as total_revenue
        FROM order_items oi
        INNER JOIN meals m ON oi.meal_id = m.meal_id
        INNER JOIN orders o ON oi.order_id = o.order_id
        WHERE MONTH(o.order_date) = :month 
        AND YEAR(o.order_date) = :year
        AND o.order_status = 'Delivered'
        GROUP BY m.meal_id
        ORDER BY total_quantity DESC
        LIMIT 10
    ");
    
    $bestSellersStmt->execute(['month' => $month, 'year' => $year]);
    $bestSellers = $bestSellersStmt->fetchAll();
    
    $monthName = date('F', mktime(0, 0, 0, $month, 1));
    
    // Set headers for PDF download
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="sales-report-' . $month . '-' . $year . '.pdf"');
    
    // For this demo, we'll create a simple text-based PDF simulation
    // In production, use TCPDF or similar library
    
    $content = "
    ================================================================================
    AUNT JOY'S RESTAURANT - SALES REPORT
    ================================================================================
    
    Report Period: $monthName $year
    Generated: " . date('F j, Y, g:i a') . "
    Generated By: " . $_SESSION['full_name'] . "
    
    ================================================================================
    SUMMARY STATISTICS
    ================================================================================
    
    Total Revenue:           " . formatCurrency($summary['total_revenue'] ?? 0) . "
    Total Orders:            " . ($summary['total_orders'] ?? 0) . "
    Average Order Value:     " . formatCurrency($summary['average_order_value'] ?? 0) . "
    
    ================================================================================
    TOP SELLING ITEMS
    ================================================================================
    
    Rank  Item Name                         Quantity    Revenue
    ----  ---------------------------------  ---------   ------------------
    ";
    
    $rank = 1;
    foreach ($bestSellers as $item) {
        $content .= sprintf(
            "%-4s  %-33s  %-9s   %s\n",
            $rank++,
            substr($item['meal_name'], 0, 33),
            $item['total_quantity'],
            formatCurrency($item['total_revenue'])
        );
    }
    
    $content .= "
    ================================================================================
    
    This is an automated report generated by Aunt Joy's Restaurant Management System.
    For questions or clarifications, please contact the manager.
    
    © " . date('Y') . " Aunt Joy's Restaurant. All rights reserved.
    ================================================================================
    ";
    
    // Output the content
    echo $content;
    exit();
    
} catch (PDOException $e) {
    die('Failed to generate PDF: ' . $e->getMessage());
}

/**
 * NOTE: To implement proper PDF generation, install TCPDF:
 * 
 * 1. Download TCPDF from https://tcpdf.org/
 * 2. Extract to your project
 * 3. Use this code instead:
 * 
 * require_once('tcpdf/tcpdf.php');
 * 
 * $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8');
 * $pdf->SetCreator('Aunt Joy\'s Restaurant');
 * $pdf->SetTitle('Sales Report');
 * $pdf->AddPage();
 * $pdf->SetFont('helvetica', '', 12);
 * $pdf->Write(0, $content, '', 0, 'L', true);
 * $pdf->Output('sales-report.pdf', 'D');
 */
?>