<?php
/**
 * Export PDF Controller
 * Exports sales report to PDF format using TCPDF
 */

require_once '../../config/db.php';
require_once '../../vendor/tcpdf/tcpdf.php';

// Check authentication and authorization
if (!isLoggedIn()) {
    die(json_encode(['success' => false, 'message' => 'Unauthorized - Please log in']));
}

if (!hasRole('Manager', 'Administrator')) {
    die(json_encode(['success' => false, 'message' => 'Access denied - Manager role required']));
}

$month = $_GET['month'] ?? null;
$year = $_GET['year'] ?? null;

if (!$month || !$year) {
    die('Month and year are required');
}

try {
    $db = getDB();
    
    // Get report data
    $summaryStmt = $db->prepare("
        SELECT 
            COUNT(*) as total_orders,
            SUM(total_amount) as total_revenue,
            AVG(total_amount) as average_order_value
        FROM orders
        WHERE MONTH(order_date) = :month 
        AND YEAR(order_date) = :year
        AND order_status = 'Delivered'
    ");
    
    $summaryStmt->execute(['month' => $month, 'year' => $year]);
    $summary = $summaryStmt->fetch();
    
    // Get best sellers
    $bestSellersStmt = $db->prepare("
        SELECT 
            m.meal_name,
            SUM(oi.quantity) as total_quantity,
            SUM(oi.subtotal) as total_revenue
        FROM order_items oi
        INNER JOIN meals m ON oi.meal_id = m.meal_id
        INNER JOIN orders o ON oi.order_id = o.order_id
        WHERE MONTH(o.order_date) = :month 
        AND YEAR(o.order_date) = :year
        AND o.order_status = 'Delivered'
        GROUP BY m.meal_id
        ORDER BY total_quantity DESC
        LIMIT 10
    ");
    
    $bestSellersStmt->execute(['month' => $month, 'year' => $year]);
    $bestSellers = $bestSellersStmt->fetchAll();
    
    $monthName = date('F', mktime(0, 0, 0, $month, 1));
    
    // Create new PDF document
    $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8');
    
    // Set document information
    $pdf->SetCreator('Aunt Joy\'s Restaurant Management System');
    $pdf->SetAuthor($_SESSION['full_name'] ?? 'Manager');
    $pdf->SetTitle('Sales Report - ' . $monthName . ' ' . $year);
    $pdf->SetSubject('Monthly Sales Report');
    
    // Set default header data
    $pdf->SetHeaderData('', 0, 'AUNT JOY\'S RESTAURANT', 'Sales Report - ' . $monthName . ' ' . $year);
    
    // Set header and footer fonts
    $pdf->setHeaderFont(Array('helvetica', '', 12));
    $pdf->setFooterFont(Array('helvetica', '', 8));
    
    // Set default monospaced font
    $pdf->SetDefaultMonospacedFont('courier');
    
    // Set margins
    $pdf->SetMargins(15, 27, 15);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    
    // Set auto page breaks
    $pdf->SetAutoPageBreak(TRUE, 25);
    
    // Set image scale factor
    $pdf->setImageScale(1.25);
    
    // Add a page
    $pdf->AddPage();
    
    // Set font
    $pdf->SetFont('helvetica', '', 11);
    
    // Report header
    $html = '
    <h1 style="text-align: center; color: #8B4513;">AUNT JOY\'S RESTAURANT</h1>
    <h2 style="text-align: center;">Monthly Sales Report</h2>
    <p style="text-align: center;"><strong>Report Period:</strong> ' . $monthName . ' ' . $year . '</p>
    <p style="text-align: center;"><strong>Generated:</strong> ' . date('F j, Y, g:i a') . '</p>
    <p style="text-align: center;"><strong>Generated By:</strong> ' . ($_SESSION['full_name'] ?? 'Manager') . '</p>
    <hr>
    ';
    
    // Summary statistics
    $html .= '
    <h3>SUMMARY STATISTICS</h3>
    <table border="1" cellpadding="5" style="border-collapse: collapse; width: 100%;">
        <tr style="background-color: #f5f5f5;">
            <th style="text-align: left;"><strong>Metric</strong></th>
            <th style="text-align: right;"><strong>Value</strong></th>
        </tr>
        <tr>
            <td>Total Revenue</td>
            <td style="text-align: right;">' . formatCurrency($summary['total_revenue'] ?? 0) . '</td>
        </tr>
        <tr>
            <td>Total Orders</td>
            <td style="text-align: right;">' . ($summary['total_orders'] ?? 0) . '</td>
        </tr>
        <tr>
            <td>Average Order Value</td>
            <td style="text-align: right;">' . formatCurrency($summary['average_order_value'] ?? 0) . '</td>
        </tr>
    </table>
    <br><br>
    ';
    
    // Top selling items
    $html .= '<h3>TOP SELLING ITEMS</h3>';
    if (!empty($bestSellers)) {
        $html .= '
        <table border="1" cellpadding="5" style="border-collapse: collapse; width: 100%;">
            <tr style="background-color: #f5f5f5;">
                <th style="text-align: center; width: 10%;"><strong>Rank</strong></th>
                <th style="text-align: left; width: 45%;"><strong>Item Name</strong></th>
                <th style="text-align: center; width: 20%;"><strong>Quantity</strong></th>
                <th style="text-align: right; width: 25%;"><strong>Revenue</strong></th>
            </tr>
        ';
        
        $rank = 1;
        foreach ($bestSellers as $item) {
            $html .= '
            <tr>
                <td style="text-align: center;">' . $rank++ . '</td>
                <td>' . htmlspecialchars($item['meal_name']) . '</td>
                <td style="text-align: center;">' . $item['total_quantity'] . '</td>
                <td style="text-align: right;">' . formatCurrency($item['total_revenue']) . '</td>
            </tr>
            ';
        }
        
        $html .= '</table>';
    } else {
        $html .= '<p>No sales data available for the selected period.</p>';
    }
    
    // Footer
    $html .= '
    <br><br>
    <hr>
    <p style="text-align: center; font-size: 10px; color: #666;">
        This is an automated report generated by Aunt Joy\'s Restaurant Management System.<br>
        For questions or clarifications, please contact the manager.<br><br>
        © ' . date('Y') . ' Aunt Joy\'s Restaurant. All rights reserved.
    </p>
    ';
    
    // Print text using writeHTMLCell()
    $pdf->writeHTML($html, true, false, true, false, '');
    
    // Close and output PDF document
    $filename = 'sales-report-' . $month . '-' . $year . '.pdf';
    $pdf->Output($filename, 'D');
    exit();
    
} catch (PDOException $e) {
    die('Failed to generate PDF: ' . $e->getMessage());
} catch (Exception $e) {
    die('PDF generation error: ' . $e->getMessage());
}
?>